version: "3.7"
services:
  discordstats:
    image: 'quay.io/fofgaming/discordstats:latest'
    networks:
      - fofnet
    environment:
      - DISCORD_BOT_TOKEN
      - DB_CONNECTION_STRING
      - ROLLBAR_TOKEN
    restart: always
networks:
  fofnet:
