version: "3.7"
services:
  discordstats:
    image: 'quay.io/fofgaming/discordstats:latest'
    networks:
      - fofnet
    volumes:
      - ${MYSQL_SOCKET_PATH}:/var/run/mysqld/mysqld.sock
    environment:
      - DISCORD_BOT_TOKEN
      - DB_CONNECTION_STRING
      - ENVIRONMENT=${FOF_ENV}
      - ROLLBAR_TOKEN=${DISCORD_STATS_ROLLBAR_TOKEN}
    restart: always
networks:
  fofnet:
